### ISSUE TITLE
Update DL1 json file

### ISSUE THREAD

**Issue by dguest** [atlas-flavor-tagging-algo/Athena-retagging-setup#1]
The format for the DL1 json file has changed since it was last updated. At some point we should regenerate it so that the tagger works out of the box.

**Comment by malanfer** [comment]
I'll work on a python/shell script to take care of this. Might be nice to bundle the whole NN config file together just by pressing enter. 
Might take a few days though till I get to take time to do this.

**Comment by dguest** [comment]
I don't think we need any additional scripts, just a json file that works with the current version of the NN (I don't think we need to make this package depend on lwtnn). But in line with #2, it's probably also worth putting that file somewhere universally accessible and having this script call `wget` or something.

**Comment by malanfer** [comment]
There is no need for a AFS -->`wget` change at this point. AFS works just fine. 

I updated the storage directory to include a NN dummy for DL1 with 3 output nodes and also check variables in the inputs. The link which the JO points to is updated to point to this file.
